import { TokenMetadata } from '../src/index.js';

test('token metadata native SAC', () => {
  const xdr_string =
    'AAAABgAAAAAAAAABfcHs35M1GZ/JkY2+DHMs4dEUaqjynMnDYK/Gp0eulN8AAAAUAAAAAQAAABMAAAABAAAAAQAAAAIAAAAPAAAACE1FVEFEQVRBAAAAEQAAAAEAAAADAAAADwAAAAdkZWNpbWFsAAAAAAMAAAAHAAAADwAAAARuYW1lAAAADgAAAAZuYXRpdmUAAAAAAA8AAAAGc3ltYm9sAAAAAAAOAAAABm5hdGl2ZQAAAAAAEAAAAAEAAAABAAAADwAAAAlBc3NldEluZm8AAAAAAAAQAAAAAQAAAAEAAAAPAAAABk5hdGl2ZQAA';
  const resouces = TokenMetadata.fromLedgerEntryData(xdr_string);
  expect(resouces.name).toEqual('native');
  expect(resouces.symbol).toEqual('XLM');
  expect(resouces.decimals).toEqual(7);
  expect(resouces.asset?.getCode()).toEqual('XLM');
  expect(resouces.asset?.getIssuer()).toEqual(undefined);
});

test('token metadata custom SAC', () => {
  const xdr_string =
    'AAAABgAAAAAAAAABHsxmivPs1zwV/XHCKqJ8XrEw9n8DKvsM5V9n74jGX2IAAAAUAAAAAQAAABMAAAABAAAAAQAAAAMAAAAPAAAACE1FVEFEQVRBAAAAEQAAAAEAAAADAAAADwAAAAdkZWNpbWFsAAAAAAMAAAAHAAAADwAAAARuYW1lAAAADgAAAD1VU0RDOkdDRFVRUTJMUDJNMzJRNTYzWU9KT0czNktYTzVUNjM1RktTV0c0SVFXWUZFMkZRSE1NUUtZSzNTAAAAAAAADwAAAAZzeW1ib2wAAAAAAA4AAAAEVVNEQwAAABAAAAABAAAAAQAAAA8AAAAFQWRtaW4AAAAAAAASAAAAAAAAAACHSENLfpm9Q77eHJcbflXd2ft9KqVjcRC2Ck0WB2MgrAAAABAAAAABAAAAAQAAAA8AAAAJQXNzZXRJbmZvAAAAAAAAEAAAAAEAAAACAAAADwAAAAlBbHBoYU51bTQAAAAAAAARAAAAAQAAAAIAAAAPAAAACmFzc2V0X2NvZGUAAAAAAA4AAAAEVVNEQwAAAA8AAAAGaXNzdWVyAAAAAAANAAAAIIdIQ0t+mb1Dvt4clxt+Vd3Z+30qpWNxELYKTRYHYyCs';
  const resouces = TokenMetadata.fromLedgerEntryData(xdr_string);
  expect(resouces.name).toEqual('USDC:GCDUQQ2LP2M32Q563YOJOG36KXO5T635FKSWG4IQWYFE2FQHMMQKYK3S');
  expect(resouces.symbol).toEqual('USDC');
  expect(resouces.decimals).toEqual(7);
  expect(resouces.asset?.getCode()).toEqual('USDC');
  expect(resouces.asset?.getIssuer()).toEqual(
    'GCDUQQ2LP2M32Q563YOJOG36KXO5T635FKSWG4IQWYFE2FQHMMQKYK3S'
  );
});

test('token metadata custom token', () => {
  const xdr_string =
    'AAAABgAAAAAAAAAB4dYEmWK0SjS2+BlO99WqstiY5TunBYL/2bCwjWxYiDIAAAAUAAAAAQAAABMAAAAAzwaZl8yVZ3yO2F1nVH3CkbRQJzsMqJQOrqF6u4sXqVoAAAABAAAABwAAAA8AAAAITUVUQURBVEEAAAARAAAAAQAAAAMAAAAPAAAAB2RlY2ltYWwAAAAAAwAAAAcAAAAPAAAABG5hbWUAAAAOAAAAEENvbWV0IFBvb2wgVG9rZW4AAAAPAAAABnN5bWJvbAAAAAAADgAAAARDUEFMAAAAEAAAAAEAAAABAAAADwAAAAVBZG1pbgAAAAAAABIAAAAB4dYEmWK0SjS2+BlO99WqstiY5TunBYL/2bCwjWxYiDIAAAAQAAAAAQAAAAEAAAAPAAAAB0ZhY3RvcnkAAAAAEgAAAAF25M0LgmD1pFOKcrlZA+95jqBVRoxE+zSwLOMEfhF0jwAAABAAAAABAAAAAQAAAA8AAAAIRmluYWxpemUAAAAAAAAAAQAAABAAAAABAAAAAQAAAA8AAAAKUHVibGljU3dhcAAAAAAAAAAAAAEAAAAQAAAAAQAAAAEAAAAPAAAAB1N3YXBGZWUAAAAACgAAAAAAAAAAAAAAAAAAdTAAAAAQAAAAAQAAAAEAAAAPAAAAC1RvdGFsV2VpZ2h0AAAAAAoAAAAAAAAAAAAAAAAF9eEA';
  const resouces = TokenMetadata.fromLedgerEntryData(xdr_string);
  expect(resouces.name).toEqual('Comet Pool Token');
  expect(resouces.symbol).toEqual('CPAL');
  expect(resouces.decimals).toEqual(7);
  expect(resouces.asset).toEqual(undefined);
});
