import { Q4W } from '../../src/backstop/Q4W';

test('convert xdr to Q4W array', () => {
  const to_convert =
    'AAAABqpZ67X1xfp+OuPHDkNzVB7sMssJOnF0+gqi769JNZWwAAAAEAAAAAEAAAACAAAADwAAAANRNFcAAAAAEQAAAAEAAAACAAAADwAAAARwb29sAAAADQAAACAPom+Tn3CdPUU0ZRVHtU6eu1DiRg5AxAP9fR4mtGRSSgAAAA8AAAAEdXNlcgAAABMAAAAAAAAAADtx8/M9buSVsoTdgKHc0SpsdaX2sUBlLTugW2c6IRE6AAAAEAAAAAEAAAABAAAAEQAAAAEAAAACAAAADwAAAAZhbW91bnQAAAAAAAoAAAAcvjGCgAAAAAAAAAAAAAAADwAAAANleHAAAAAABQAAAABkao4z';

  const result = Q4W.fromXDR(to_convert);
  expect(result).toEqual([new Q4W(BigInt('123450000000'), 1684704819)]);
});
